### ISSUE TITLE
When multiple transfers are uploaded at once, user does not receive email notifications for all of them.

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#116]
Gathering data and troubleshooting this.

**Comment by helrond** [comment]
When more than five bags are discovered by the application, the user only receives emails for the first five bags discovered. Does this point to some sort of rate limit on the SMTP side?

**Comment by dboutmybizness** [comment]
I believe I fixed this with some logic updates in an already merged branch (filesize)..

**Comment by dboutmybizness** [comment]
Let me test out that theory.

**Comment by helrond** [comment]
Update: testing code currently deployed on live site, I am now getting emails for the first nine bags discovered (as opposed to the first five), so there seems to have been some improvement, although the problem is not fully resolved.

**Comment by HaSistrunk** [comment]
Notifications through the app are no longer required - closing this issue
