### ISSUE TITLE
Transfer table does not sort sizes correctly

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#646]
## Describe the bug
Transfer sizes are not sorted correctly in the transfers table. They are sorted by number regardless of unit (KB, MB or GB)

## To reproduce
1. Sort the transfers table by size in Aurora prod and you'll see something like the following:

<img width="71" alt="Screen Shot of mis-sorted transfer sizes" src="https://github.com/RockefellerArchiveCenter/aurora/assets/607621/042752e5-0855-441a-8426-36d4580b755c">

## Expected behavior
Transfers should be sorted correctly by size regardless of units used.

## Impact on your work
Not a huge deal but would be good to get sorted out.

**Comment by helrond** [comment]
From initial research it appears that this is happening because the number in the `machine_file_size` field exceeds the Javascript `MAX_SAFE_INTEGER`. Datatables suggests using [orthogonal data](https://datatables.net/examples/ajax/orthogonal-data) however this approach is throwing an error in the `filter_queryset` method of the `DatatableMixin`. This could likely be solved by updating the library which supports the server-side rendering for Datatables (see, for example, the [`django_datatable_serverside_mixin`](https://github.com/matthttam/django_datatable_serverside_mixin).

**Comment by HaSistrunk** [comment]
Initially decided to remove the sort capability on that column in PR #683 thinking that the sort functionality was not worth the work-around. However, user feedback has indicated that sorting by file size is useful - so let's see if we can figure out a workable solution for this.

**Comment by HaSistrunk** [comment]
Update: I tried using orthogonal data that uses `file_size(int(transfer.machine_file_size))` as the display and `int(transfer.machine_file_size)` as the sort value, but that did not solve the issue (see [0abcdea](https://github.com/RockefellerArchiveCenter/aurora/pull/683/commits/0abcdea1b867ebe9b629cd9bf7a782b68ded7b3d) and [1c47def](https://github.com/RockefellerArchiveCenter/aurora/pull/683/commits/1c47defa26c5667b656fc88ae44efe461f0262d9)). I also tried implementing the https://datatables.net/plug-ins/sorting/file-size plugin, which also did not fix the issue.

I can't confirm that the issue is related to the number in the `machine_file_size` field exceeding the Javascript `MAX_SAFE_INTEGER`. 9007199254740991 is apparently that number, and the highest number in the sample data that I'm testing with is 8602184.

@helrond , any ideas on how to solve this?
